# These are supported funding model platforms

github: [heyshinde]
patreon: heyshinde
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: pypi/torch-secorder
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: heyshinde
thanks_dev: #update with a thanks dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
